#!/usr/bin/env bash
#
# Author: Lars Hupel
#
# DESCRIPTION: perform opam setup

set -e

SWITCH="ocaml-base-compiler.$ISABELLE_OCAML_VERSION"

isabelle_opam init --quiet --no-setup --no-opamrc
if ! ( isabelle_opam switch list -s | grep -q -F "$SWITCH" ); then
  isabelle_opam switch create "$SWITCH"
fi
isabelle_opam switch --quiet set "$SWITCH" >/dev/null
